import pandas as pd
import sys
sys.path.append("..")
from utils.title_filter import filter_titles_by_phrases

EXCLUSION_PHRASES = [
    'drug-drug', 'drug-target interaction', 'drug responses', 'drug discovery', 'molecular medicine', 'molecules', 'molecule',
    'drug repositioning', 'adverse drug event', 'drug sensitivity', 'drug repurposing',
    'treatment outcomes', 'medication prediction based on reviews', 'drug function extraction',
    'drug information extraction', 'safety information', 'genetics', 'genomics', 'genomic', 'molecular',
    'drug-disease association', 'drug synergy', 'drug resistance', 'drug efficacy',
    'drug demand and supply', 'pharmaceutical needs', 'drug side effects', 'drug-side' 'drug interactions',
    'drug property prediction', 'precision medicine', 'sentiment', 'chinese', 'tcm', 'ayurveda', 'homeopathy', "herbal medicine",
    'traditional', 'Patient Similarity Analysis', 'repurpose', 'repurposing', 'repurposed', 'sepsis antibiotic dosing', 'management',
    'kampo', 'response', 'mortality', 'package', 'genes', 'metagenomics', 'event prediction', 'target', 'marker', 'protein', 'tumor',
    'disease prediction', 'drug effects', 'cancer', 'allergy', 'hospital stay', 'hospitalization', 'readmission',
    'medication effectiveness prediction', 'disorder', 'disorders', 'kidney', 'diabetes', 'cardiovascular', 'cardiovascular disease',
    'disease', 'adherence', 'alzheimer', 'medication orders', 'pediatric', 'medication alert',
    'adverse', 'anatomical', 'sales', 'hepatotoxicity', 'electron density prediction',
    'anesthesia', 'interaction', 'interactions', 'overdose', 'gene', 'property', 'drug profiles', 'pharmacokinetics', 'pharmacokinetic',
    'pharmacodynamics', 'pharmacodynamic', 'arrhythmia', 'side-effects', 'side-effect', 'COVID-19', 'COVID', 'SARS-CoV-2', 'SARS-CoV',
    'drug profile', 'phenotype', 'microbes', 'microbiome', 'microbiota', 'microbe', 'microbial community', 'discovery', 
    'anticancer', 'solubility', 'liver', 'synergy', 'alcohol', 'drug event', 'drug design', 'respiratory',
    'compound activity', 'structure', 'arthritis', 'effectiveness', 'ventricular', 'cell',
    'antiviral', 'antibiotic', 'antibiotics', 'antimicrobial', 'antimicrobials', 'antifungal', 'antifungals',
    'chemogenomics', 'specificity', 'absorption', 'biomarker', 'multi-omics', 'multiomics', 
    'procurement', 'bioactivity', 'chemoinformatics', 'autophagy', 'drug function', 'inhibitors', 
    'nephrotoxicity', 'drug activity', 'influenza', 'targets', 'food', 'carcinoma', 'pregnancy',
    'tuberculosis', 'risk', 'scaphocephaly', 'brain', 'dementia', 'sclerosis', 'fractures', 'fracture',
    'injury', 'sleep', 'biomarker', 'biomarkers', 'sepsis', 'hematoma', 'delirium', 'survival prediction', 'survival',
    'fibrillation', 'trauma', 'pain', 'bones', 'bone', 'athlete', 'surgery', 'aging prediction',
    'glucose', 'expenditure Prediction', 'cardiorespiratory', 'mental', 'lung', 'dental', 'proteins',
    'diseases', 'injuries', 'cardiac', 'meningioma', 'seizures', 'malaise', 'dentistry', 'seizure',
    'fatigue', 'markets', 'asthma', 'revenue', 'hypertension', 'osteoporosis', 'bioinformatics',
    'colon', 'allergic', 'mutations', 'mutation', 'pharmacogenomic', "Parkinson’s", 'prognosis',
    'melanoma', 'varicose vein', 'veins', 'side effects', 'side effect', 'pathogenic', 'vascular',
    'vitamin', 'oncology', 'nausea', 'ARDS', 'myocardial', 'appendicitis', 'inhibitor', 'inhibitors','telehealth'
]

EXCLUDED_TITLES = ['Negative-sample-free knowledge graph embedding',
                   'Comparative analysis of cell line similarity algorithms in oncology treatment',
                   'Multi-task heterogeneous graph learning on electronic health records',
                   'Enhancing Neural Recommender Models through Domain-Specific Concordance',
                   'Uplift Modeling with Generalization Guarantees',
                   'Bioinformatics-Based Identification of lncRNA-miRNA-mRNA Network in Dilated Cardiomyopathy and Drug Prediction',
                   'Fuzzy based medicine recommendation system: an example of thyroid medicine',
                   'Symptom-based drug prediction of lifestyle-related chronic diseases using unsupervised machine learning techniques',
                   'Clinical decision support system for hypertension medication based on knowledge graph',
                   'Context-Awareness Based Personalized Recommendation of Anti-Hypertension Drugs',
                   'Predictive Approaches for Low-Cost Preventive Medicine Program in Developing Countries',
                   'Comparing Drug-Disease Associations in Clinical Practice Guideline',
                   'Multiple Kronecker {RLS} fusion-based link propagation for drug-side',
                   'A general hypergraph learning algorithm for drug multi-task predictions',
                   'TransEDRP: Dual Transformer model with Edge Emdedded for Drug Respond',
                   'Prediction of Drug Users Based on Facial Scratching Pattern',
                   'Factors influencing Drug Consumption and Prediction Methods',
                   'Drug Similarity and Link Prediction Using Graph Embeddings on Medical',
                   'Maximum Phase Modeling for Sparse Linear Prediction of Speech',
                   'OAPRS:} An Online Agriculture Prescription Recommendation System',
                   'How to translate therapeutic recommendations in clinical practice',
                   'Using digital technologies to diagnose in the home: recommendations',
                   'Translating clinical trial results into personalized recommendations',
                   'Proceedings of the Joint Proceedings of Reasoning with Ambiguous and',
                   'Dual attention based fusion network for {MCI} Conversion Prediction',
                   'Prediction of the effect of electrical defibrillation by using spectral',
                   'Personalized mood prediction from patterns of behavior collected with',
                   'Prediction of total and regional body composition from 3D body shape',
                   'Zero shot health trajectory prediction using transformer',
                   'a Benchmark Dataset for Diagnoses and Deterioration Prediction',
                   'Tree-based explanations of machine',
                   'real-time individualized endpoint prediction',
                   'inter-chain contact prediction',
                   'Fetal birth weight prediction',
                   'Automatic yet eXplainable Age and Sex determination',
                   'A prediction model of qi stagnation',
                   'prediction of demographics in medical imaging',
                   'Bacterial Type {III} Secreted Effectors',
                   'Prediction of Daily Blood Sampling Room Visits',
                   'Machine-learning-based prediction models for high-need high-cost patients',
                   'Heart Failure Prediction',
                   'Prediction in Intensive Care Unit',
                   'daily living activities', 
                   'Prediction of Pathological Subjects',
                   'GPCR-Ligand Binding', 'Advertising', 'Prediction of {BP} Reactivity',
                   'Length of Lumbar Puncture Needles', 'Balance Prediction',
                   'Automated Conduction Velocity Analysis',
                   'Clinical Outcome Prediction',
                   'Heavy-Tailed Prediction Error: {A} Difficulty in Predicting Biomedical',
                   'Prediction of Breeding Values for Dairy Cattle',
                   'Locomotor Development Prediction',
                   'Prediction of {HCV} Therapy Efficiency',
                   'Automated {MRI} Field of View Prescription',
                   'PDPN contributes to constructing immunosuppressive microenvironment in IDH wildtype glioma',
                   'Transdiagnostic clustering and network analysis',
                   'Novel sex-specific influence of parental factors on small-for-gestational-age newborns',
                   'Gestational weight gain and visceral adiposity in adult offspring',
                   'A Robust Method for Inferring Network Structures',
                   'Modeling electronic health record data using an end-to-end knowledge-graph-informed topic model',
                   'Mapping the effects of drugs on the immune system',
                   'medicinal herbs',
                   'prediction of hyperspectral images',
                   'remote patient monitoring with IoT',
                   'CDCDB: A large and continuously updated drug combination database',
                   'Multilabel classification for defect prediction in software engineering',
                   'ACNP 56th Annual Meeting',
                   'human judgment',
                   'ClOud-based MEdicine Recommendation',
                   'Personalized Medicine Recommendation Based on Tensor Decomposition'
                   ]

FULL_EXECUTION = EXCLUSION_PHRASES + EXCLUDED_TITLES
def main():
    df = pd.read_csv('../data/all_papers_dedup.csv')
    kept, removed = filter_titles_by_phrases(df, FULL_EXECUTION, title_col='title')
    kept.to_csv('../data/all_papers_filtered.csv', index=False)
    removed.to_csv('../data/all_papers_removed.csv', index=False)
    print(f"Filtered: {len(kept)} kept, {len(removed)} removed. Saved to ../data/") # 907, 325

if __name__ == "__main__":
    main()
